version: 0.2

phases:
  install:
    commands:
      - echo Installing NVM and Node.js 22.16.0
      - |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
        export NVM_DIR="$HOME/.nvm" && \
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
        nvm install 22.16.0 && \
        nvm use 22.16.0 && \
        node -v
  build:
    commands:
      - |
        export NVM_DIR="$HOME/.nvm" && \
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
        nvm use 22.16.0 && \
        npm run deb_project

artifacts:
  files:
    - release-packages/**/*
